module.exports = {
  BasePage: require('./BasePage'),
  DashboardPage: require('./DashboardPage'),
  LoginPage: require('./LoginPage'),
  ProductPage: require('./ProductPage'),
  CategoryPage: require('./CategoryPage'),
  AttributePage: require('./AttributePage'),
  AttributeFamilyPage: require('./AttributeFamilyPage'),
  AttributeGroupPage: require('./AttributeGroupPage'),
  CategoryFieldPage: require('./CategoryFieldPage'),
  MeasurementPage: require('./MeasurementPage'),
  AssociationTypePage: require('./AssociationTypePage'),
  ChannelPage: require('./ChannelPage'),
  CurrencyPage: require('./CurrencyPage'),
  LocalePage: require('./LocalePage'),
  RolePage: require('./RolePage'),
  UserPage: require('./UserPage'),
  IntegrationPage: require('./IntegrationPage'),
  WebhookPage: require('./WebhookPage'),
  MagicAIPage: require('./MagicAIPage'),
  ExportPage: require('./ExportPage'),
  ImportPage: require('./ImportPage'),
  JobTrackerPage: require('./JobTrackerPage'),
  NotificationPage: require('./NotificationPage'),
  MyAccountPage: require('./MyAccountPage'),
};
